//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training140417
{
    using System;
    using System.Collections.Generic;
    
    public partial class uploadfile
    {
        public int id { get; set; }
        public string filename { get; set; }
        public byte[] content { get; set; }
        public string contenttype { get; set; }
    }
}
